version: 0.0
os: linux
files:
  - source: ./mkyong.war
    destination: /opt/tomcat/webapps/
    overwrite: true
permissions:
  - object: /opt/tomcat/webapps
    pattern: "*.war"
    owner: tomcat
    group: tomcat
    mode: 766
    type:
      - file